# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml              # Vérifie que les fichiers YAML sont valides
      - id: check-toml              # Vérifie que les fichiers TOML sont valides
      - id: end-of-file-fixer       # Ajoute une ligne vide à la fin des fichiers si nécessaire
      - id: trailing-whitespace     # Supprime les espaces inutiles à la fin des lignes
      - id: check-added-large-files # Avertit si de gros fichiers sont ajoutés
        exclude: ^(docs/|site/)

  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.12.9
    hooks:
    # Apply Ruff linting fixes.
    - id: ruff
      name: ruff fix # We can add arbitrary names to our hooks
      args: [--fix]
      types_or: [python, pyi] # Only scan .py files (and not jupyter notebooks)

    # Run the formatter.
    - id: ruff-format
      name: ruff format
      types_or: [python, pyi] # Only format .py files (and not jupyter notebooks)

    # Run the linter one last time to check for remaining issues.
    - id: ruff
      name: ruff check
      args: [--output-format, concise] # Makes the ruff check output more legible.
      types_or: [python, pyi] # Only scan .py files (and not jupyter notebooks)
